### ISSUE TITLE
access_token KeyError

### ISSUE THREAD

**Issue by ToranBrown** [arjenvrh/audi_connect_ha#105]
### Updated to HACS 19.2 today and upon restarting the Core, received the following error:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_services.py:241
Integration: Audi Connect
First occurred: 10:38:47 AM (1 occurrences)
Last logged: 10:38:47 AM

Error setting up entry xxx@xxx.com for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 241, in get_vehicle_information
    "Authorization": "Bearer " + self.audiToken["access_token"],
KeyError: 'access_token'

### Pehraps something has changed on the AudiConnect side?  Please let me know if you need additional information regarding my configuration.

**Comment by shuntfield** [comment]
Did a restart of HA as it needed to do a core update - getting the same

`KeyError: 'access_token'`

Though I notice the app on my Android Phone has been a bit shakey of late too.

**Comment by ToranBrown** [comment]
I updated to 2021.12.9 this morning and upon restarting Core, the error ceased and the integration is now working properly.
