### ISSUE TITLE
Login error - Fixed

### ISSUE THREAD

**Issue by bartpaeleman** [arjenvrh/audi_connect_ha#155]
After upgrade to 2022.10 getting error on credentials to log in:

Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_services.py:261
Integration: Audi Connect
First occurred: 09:06:31 (1 occurrences)
Last logged: 09:06:31

Error setting up entry my@emailaddress for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 261, in get_vehicle_information
    vins = json.loads(rep_rsptxt)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bartpaeleman** [comment]
Seems to have fixed itself on its own.
