### ISSUE TITLE
new login issue?

### ISSUE THREAD

**Issue by pilot1981** [arjenvrh/audi_connect_ha#176]
Hi,
today I see this new issue:

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: Cannot connect to host content.app.my.audi.com:443 ssl:default [Try again]
Login to Audi service failed: 'client_id'
Login to Audi service failed: [Errno 104] Connection reset by peer

any idea?

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_api.py:53
Integration: Audi Connect (documentation, issues)
First occurred: 16:28:17 (1 occurrences)
Last logged: 16:28:17

Cannot connect to host app-api.live-my.audi.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 251, in get_vehicle_information
    req_rsp, rep_rsptxt = await self._api.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 53, in request
    async with self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host app-api.live-my.audi.com:443 ssl:default [Try again]

**Comment by Realmlist** [comment]
Problems on VW's backend. If you log into myAudi on the website they tell you there's an outage.

**Comment by pilot1981** [comment]
this custom omponente is very useful but:
- it's very slow to send comand to car
- I have problem veery oftn with this integration

**Comment by Realmlist** [comment]
The Audi Connect API has been changing a lot lately, it can become very bothersome to keep up.

At this moment VW/Audi is having server issues. Unfortunately all we can do is wait until their servers work again.

**Comment by synack666** [comment]
Late in the evening it worked here again.
