### ISSUE TITLE
Audi Connect integration and upgrade to Home Assistant Core Version: 2023.9.3

### ISSUE THREAD

**Issue by hhoehler** [arjenvrh/audi_connect_ha#202]
Hi, the Audi Connect integration doesn´t work after the upgrade to Home Assistant Core Version: 2023.9.3 for me.

Please find the error protocol attached:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 53, in request
    async with self._session.request(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 52, in request
    with async_timeout.timeout(TIMEOUT):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 128, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 251, in get_vehicle_information
    req_rsp, rep_rsptxt = await self._api.request(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_api.py", line 75, in request
    raise TimeoutError("Timeout error")
TimeoutError: Timeout error

**Comment by hhoehler** [comment]
For some reason it works again.
