### ISSUE TITLE
audiconnect.execute_vehicle_action start_preheater not working

### ISSUE THREAD

**Issue by mhgoedings** [arjenvrh/audi_connect_ha#215]
Hi, i am trying to automate the pre-heating of my etron. When I call the audiconnect.execute_vehicle_action service with VIN and start_preheater command the service returns a green check mark, but the pre-heating does not start.
When I run in debug modus the error message below is given. Does anybody know what is happening here?
Best regards, Michael

2023-12-23 11:07:31.274 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state for sensor.etron_shortterm_trip_user_reset, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 872, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1732, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1309, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 193, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 285. State max length is 255 characters.

**Comment by jocxfin** [comment]
Hi, was just wondering if your car supports pre-heating...have you tried start_climatisation instead of start_preheater? Seems like the errors you're getting are the same ones I had and I found a solution for that particular issue. Discussion here: [https://github.com/arjenvrh/audi_connect_ha/issues/213#issuecomment-1868290487](https://github.com/arjenvrh/audi_connect_ha/issues/213#issuecomment-1868290487)

**Comment by mhgoedings** [comment]
Hi joxfin, I tried audiconnect.execute_vehicle_action start_climatisation and this works!! In hindsight I should have tried this one myself...had no idea this is an alternative.
Thanks a million! Michael
