### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by micky2171** [arjenvrh/audi_connect_ha#216]
Stopped working about a month ago, just never got the chance to look at it.

There is no `# "device_type": "device_tracker",` on line 124 in device_tracker.py
and no `"device_type": self._component,` on line 80 in audi_entity.py

All states are showing as unavailable except Model.

Debugging shows:

> 2024-01-12 13:19:16.502 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1177, in async_schedule_update_ha_state
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/config/custom_components/audiconnect/sensor.py", line 35, in state
>     return self._instrument.state
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/audiconnect/dashboard.py", line 155, in state
>     val = super().state
>           ^^^^^^^^^^^^^
>   File "/config/custom_components/audiconnect/dashboard.py", line 119, in state
>     if hasattr(self._vehicle, self._attr):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/audiconnect/audi_connect_account.py", line 1203, in actual_charge_rate
>     return parse_float(self._vehicle.state.get("actualChargeRate"))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/audiconnect/util.py", line 37, in parse_float
>     return float(val)
>            ^^^^^^^^^^
> TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by micky2171** [comment]
Works after updating it in HACS
