### ISSUE TITLE
Doesn't work anymore. 'Unauthorized'

### ISSUE THREAD

**Issue by DenisBY** [arjenvrh/audi_connect_ha#33]
It seems Audi has changes something and now it doesn't work anymore:
```
2020-05-18 08:25:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_account.py", line 158, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 129, in get_vehicle_information
    "https://msg.audi.de/myaudi/vehicle-management/v1/vehicles"
  File "/config/custom_components/audiconnect/audi_api.py", line 54, in get
    r = await self.request(METH_GET, url, data=None, headers=self.__get_headers())
  File "/config/custom_components/audiconnect/audi_api.py", line 46, in request
    message=response.reason,
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url='https://msg.audi.de/myaudi/vehicle-management/v1/vehicles
```

**Comment by heymoe** [comment]
I'd try removing and re-adding the integration if you haven't already and see if that get you up and running again.
