### ISSUE TITLE
Integration Stopped working 

### ISSUE THREAD

**Issue by shuntfield** [arjenvrh/audi_connect_ha#39]
Hi

Is anyone getting the same problem, it looks like this has stopped working for me.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 220, in async_setup
    hass, self
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 158, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 125, in get_vehicle_information
    "https://msg.audi.de/myaudi/vehicle-management/v1/vehicles"
  File "/config/custom_components/audiconnect/audi_api.py", line 54, in get
    r = await self.request(METH_GET, url, data=None, headers=self.__get_headers())
  File "/config/custom_components/audiconnect/audi_api.py", line 46, in request
    message=response.reason,
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url='https://msg.audi.de/myaudi/vehicle-management/v1/vehicles`

This is all that I am getting in the logs.

I removed and reinstalled the integration but it still fails, working perfectly up until today, my Audi is still working fine though.

Thanks

**Comment by shuntfield** [comment]
Must have had a remote end problem ok now.
