### ISSUE TITLE
CancelledError / TimeoutError / TimeoutError: Timeout error

### ISSUE THREAD

**Issue by tnaumann71** [arjenvrh/audi_connect_ha#78]
The Audi Connect Integration is currently unable to connect even after complete reinstall. I tried my credentials and they work with the Audi App and also via Web.

Here my Erro Log:
---
Error setting up entry XXXXXXXXXXXX for audiconnect
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 45, in request
    async with self._session.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 55, in request
    raise ClientResponseError(
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 194, in get_vehicle_information
    data = await self._api.get(
  File "/config/custom_components/audiconnect/audi_api.py", line 72, in get
    r = await self.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 64, in request
    raise TimeoutError("Timeout error")
asyncio.exceptions.TimeoutError: Timeout error

---

**Comment by tnaumann71** [comment]
After Updateing to Core-2021.5.2 the integration works again.
