### ISSUE TITLE
Error setting up audiconnect

### ISSUE THREAD

**Issue by dsantanu** [arjenvrh/audi_connect_ha#79]
Hi there, 

Everytime I enter the info, I get this failure: 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 194, in get_vehicle_information
    data = await self._api.get(
  File "/config/custom_components/audiconnect/audi_api.py", line 72, in get
    r = await self.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 55, in request
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://msg.audi.de/myaudi/vehicle-management/v2/vehicles')
```
What am I missing? 
Also, what is actually the S-PIN - is it the 10-digit code that comes with the key? Is it failing b'cuz of that?

-S

**Comment by otterlo** [comment]
i am having same issue whilst i had a full functional integration, i can also not login into audi anymore, perhaps Audi is having server trouble

**Comment by dsantanu** [comment]
there are some issues with `my.audi.com` since this morning I think; it's slow but can login eventually. But my actual question was what is exactly that **S-PIN**?

**Comment by otterlo** [comment]
I believe that s pin is available in your audi account. I was checking this right now but i cant login anynore due to server trouble

**Comment by Keulov** [comment]
same issue for me:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 194, in get_vehicle_information
    data = await self._api.get(
  File "/config/custom_components/audiconnect/audi_api.py", line 72, in get
    r = await self.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 55, in request
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://msg.audi.de/myaudi/vehicle-management/v2/vehicles')

But I don't see a problem using the connect app which is working correctly.

**Comment by Keulov** [comment]
Sorry for my last comment. Have now seen that my.audi.com isn't available.
Guess it will work after fixing maintenance.

**Comment by dsantanu** [comment]
I'm still not very sure about what that `S-PIN` is. Documentation should really explain a bit on that.

**Comment by dsantanu** [comment]
okay, I found the PIN: Now it's under **Equipment Details** in my.audi.com but something definitely wrong with this plugin now - I'm still getting this:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4650237/119203835-f646fd00-ba8b-11eb-8a12-e682e1f9c93f.png">

**Comment by dsantanu** [comment]
Okay, I take back what I said - it's working now. It started working after restarting HA.

**Comment by otterlo** [comment]
Enjoy!
